services:
  - type: web
    name: resume-ai-ml-pipeline
    env: python
    plan: free
    rootDir: ML_Preprocessor_scripts
    buildCommand: pip install -r requirements.txt && python -m spacy download en_core_web_sm
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 4 ml_api_server:app
    envVars:
      - key: PORT
        sync: false